### ISSUE TITLE
 input data grid division

### ISSUE THREAD

**Issue by endwkd** [ydc123/CNNCap#1]
Hello! We found that the input data grid division in your paper and the input data in the open source code do not match (maybe I did not understand it thoroughly), I would like to ask you to answer,thank you!

**Comment by ydc123** [comment]
Hello, thanks for your attention to our work. The input data we provide has been processed using the method described in the paper, but there is a slight difference in the encoding method compared to the paper. Specifically, according to the definition in the paper, assuming the length of the grid is L, a representation of a 3-layer case is a 3L matrix. However, storing each 3L numpy array would occupy a huge amount of disk space. To save unnecessary storage consumption, we implemented a simple compression method. It is noted that the representation in the paper often contains consecutive intervals of the same values. It can be proven that for k conductors, if adjacent values in the 3L matrix are merged together, the 3L matrix can be viewed as O(k) intervals. Each interval consisting of layer_id, l, r, and ratio, indicating the layer it belongs to, the left and right endpoints of the interval, and the value of this interval. In this way, only O(k) float32 numbers are needed to store a case, which is a significant lossless compression compared to the previous 3L float32 numbers. Then, by decoding it, you can obtain the 3L input data as described in the paper. You can refer to the code implementation at https://github.com/ydc123/CNNCap/blob/main/dataset.py#L39-L41 for understanding.
